name: aura_icon
description: "AuraIcon is a visual interface layer for emotion-aware, voice-driven, and next-gen apps. Inspired by AI interfaces, it provides dynamic animated containers for icons or widgets that signal interaction, state, and presence — with no external dependencies."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

